import type { CareerAnalysis } from "./types";

/**
 * Mock analysis used for local development only.
 *
 * This is intentionally isolated so it can be swapped out for a real AI provider
 * without touching any UI component. See `service.ts` for the abstraction.
 *
 * Note: every field carries a `source` where relevant so the UI can honestly
 * distinguish "found in resume", "inferred from project", and "not found".
 */
export const mockAnalysis: CareerAnalysis = {
  candidateName: "Not Found",
  resumeScore: 82,
  careerReadiness: 78,
  scoreBreakdown: {
    skills: 85,
    experience: 76,
    projects: 88,
    education: 90,
    ats: 72,
  },
  readiness: {
    resumeScore: 82,
    roleFit: 87,
    interviewReadiness: 71,
    skillStrength: 79,
  },
  bestRole: {
    id: "ml-engineer",
    title: "Machine Learning Engineer",
    matchScore: 87,
    summary:
      "Your strong Python foundation, hands-on ML projects, and solid math background align closely with what ML Engineering teams look for in early-career candidates.",
    matchingSkills: [
      "Python",
      "Machine Learning",
      "TensorFlow",
      "Data preprocessing",
      "ML projects",
    ],
    missingSkills: ["MLOps", "Docker", "Cloud deployment"],
  },
  recommendedRoles: [
    {
      id: "ml-engineer",
      title: "Machine Learning Engineer",
      matchScore: 87,
      summary:
        "Best overall alignment. Your ML projects and Python depth are exactly what teams screen for.",
      matchingSkills: ["Python", "Machine Learning", "TensorFlow", "Scikit-learn"],
      missingSkills: ["MLOps", "Docker", "AWS"],
      requirements: [
        { skill: "Python", yourLevel: "Strong", requiredLevel: "Strong", gap: "low" },
        { skill: "SQL", yourLevel: "Intermediate", requiredLevel: "Strong", gap: "medium" },
        { skill: "Machine Learning", yourLevel: "Strong", requiredLevel: "Strong", gap: "low" },
        { skill: "Docker", yourLevel: "Beginner", requiredLevel: "Intermediate", gap: "high" },
        { skill: "AWS", yourLevel: "Beginner", requiredLevel: "Intermediate", gap: "high" },
      ],
    },
    {
      id: "data-scientist",
      title: "Data Scientist",
      matchScore: 82,
      summary:
        "Strong statistical and modeling foundation. Sharpen SQL and experimentation for a great fit.",
      matchingSkills: ["Python", "Pandas", "Statistics", "Machine Learning"],
      missingSkills: ["A/B Testing", "Spark", "Cloud"],
      requirements: [
        { skill: "Python", yourLevel: "Strong", requiredLevel: "Strong", gap: "low" },
        { skill: "Statistics", yourLevel: "Intermediate", requiredLevel: "Strong", gap: "medium" },
        { skill: "SQL", yourLevel: "Intermediate", requiredLevel: "Strong", gap: "medium" },
        { skill: "Spark", yourLevel: "None", requiredLevel: "Intermediate", gap: "high" },
      ],
    },
    {
      id: "ai-engineer",
      title: "AI Engineer",
      matchScore: 79,
      summary:
        "Your deep learning exposure is valuable. Add deployment and LLM tooling to level up.",
      matchingSkills: ["Python", "TensorFlow", "Deep Learning", "Machine Learning"],
      missingSkills: ["LLMs", "Docker", "Cloud deployment"],
      requirements: [
        { skill: "Python", yourLevel: "Strong", requiredLevel: "Strong", gap: "low" },
        { skill: "Deep Learning", yourLevel: "Intermediate", requiredLevel: "Strong", gap: "medium" },
        { skill: "Docker", yourLevel: "Beginner", requiredLevel: "Intermediate", gap: "high" },
        { skill: "Cloud deployment", yourLevel: "Beginner", requiredLevel: "Intermediate", gap: "high" },
      ],
    },
    {
      id: "data-analyst",
      title: "Data Analyst",
      matchScore: 74,
      summary:
        "Solid analytics fundamentals. Polish dashboarding and business storytelling.",
      matchingSkills: ["Python", "Pandas", "SQL", "Data preprocessing"],
      missingSkills: ["Tableau", "Power BI", "Business Analytics"],
      requirements: [
        { skill: "SQL", yourLevel: "Intermediate", requiredLevel: "Strong", gap: "medium" },
        { skill: "Excel", yourLevel: "Intermediate", requiredLevel: "Strong", gap: "medium" },
        { skill: "Tableau", yourLevel: "None", requiredLevel: "Intermediate", gap: "high" },
      ],
    },
    {
      id: "software-engineer",
      title: "Software Engineer",
      matchScore: 68,
      summary:
        "Programming basics are strong. Deepen system design and data structures for interviews.",
      matchingSkills: ["Python", "Java", "Git", "Problem Solving"],
      missingSkills: ["System Design", "Data Structures", "Distributed Systems"],
      requirements: [
        { skill: "Data Structures", yourLevel: "Intermediate", requiredLevel: "Strong", gap: "medium" },
        { skill: "System Design", yourLevel: "Beginner", requiredLevel: "Intermediate", gap: "high" },
        { skill: "Java", yourLevel: "Intermediate", requiredLevel: "Strong", gap: "medium" },
      ],
    },
  ],
  education: [
    {
      degree: "B.Tech, Computer Science",
      university: "National Institute of Technology",
      graduationYear: "2025",
      source: "found",
    },
  ],
  experience: [
    {
      company: "DataNova Analytics",
      position: "Machine Learning Intern",
      duration: "May 2024 – Aug 2024",
      source: "found",
    },
    {
      company: "University AI Lab",
      position: "Research Assistant",
      duration: "Jan 2024 – Apr 2024",
      source: "found",
    },
  ],
  skills: [
    { name: "Python", category: "Programming", level: "Strong", source: "found" },
    { name: "Java", category: "Programming", level: "Intermediate", source: "found" },
    { name: "C++", category: "Programming", level: "Beginner", source: "found" },
    { name: "SQL", category: "Data", level: "Intermediate", source: "found" },
    { name: "Pandas", category: "Data", level: "Strong", source: "found" },
    { name: "NumPy", category: "Data", level: "Strong", source: "found" },
    { name: "Scikit-learn", category: "Machine Learning", level: "Strong", source: "found" },
    { name: "TensorFlow", category: "Machine Learning", level: "Intermediate", source: "found" },
    { name: "Deep Learning", category: "Machine Learning", level: "Intermediate", source: "inferred" },
    { name: "Git", category: "Tools", level: "Intermediate", source: "found" },
    { name: "Docker", category: "Tools", level: "Beginner", source: "not-found" },
    { name: "AWS", category: "Cloud", level: "None", source: "not-found" },
    { name: "MLOps", category: "Cloud", level: "None", source: "not-found" },
  ],
  skillGaps: [
    { skill: "Docker", category: "critical", currentLevel: "Beginner", targetLevel: "Intermediate", progress: 30 },
    { skill: "AWS", category: "critical", currentLevel: "None", targetLevel: "Intermediate", progress: 10 },
    { skill: "MLOps", category: "critical", currentLevel: "None", targetLevel: "Intermediate", progress: 12 },
    { skill: "SQL", category: "improve", currentLevel: "Intermediate", targetLevel: "Strong", progress: 62 },
    { skill: "Statistics", category: "improve", currentLevel: "Intermediate", targetLevel: "Strong", progress: 58 },
    { skill: "Deep Learning", category: "improve", currentLevel: "Intermediate", targetLevel: "Strong", progress: 55 },
    { skill: "Python", category: "strong", currentLevel: "Strong", targetLevel: "Strong", progress: 92 },
    { skill: "Machine Learning", category: "strong", currentLevel: "Strong", targetLevel: "Strong", progress: 88 },
    { skill: "Pandas", category: "strong", currentLevel: "Strong", targetLevel: "Strong", progress: 90 },
  ],
  interviewFocus: [
    {
      topic: "Machine Learning Fundamentals",
      priority: "high",
      currentLevel: "Strong",
      requiredLevel: "Strong",
      recommendation: "Revise bias-variance, regularization, and evaluation metrics end-to-end.",
    },
    {
      topic: "Python",
      priority: "high",
      currentLevel: "Strong",
      requiredLevel: "Strong",
      recommendation: "Practice writing clean, vectorized code and common data manipulation tasks.",
    },
    {
      topic: "SQL",
      priority: "high",
      currentLevel: "Intermediate",
      requiredLevel: "Strong",
      recommendation: "Drill window functions, joins, and aggregation for technical screens.",
    },
    {
      topic: "Your Projects",
      priority: "high",
      currentLevel: "Strong",
      requiredLevel: "Strong",
      recommendation: "Prepare a crisp narrative for each project: problem, approach, results, trade-offs.",
    },
    {
      topic: "Deep Learning",
      priority: "medium",
      currentLevel: "Intermediate",
      requiredLevel: "Strong",
      recommendation: "Understand backprop, CNNs/RNNs at a conceptual level.",
    },
    {
      topic: "Statistics",
      priority: "medium",
      currentLevel: "Intermediate",
      requiredLevel: "Strong",
      recommendation: "Review probability distributions, hypothesis testing, and confidence intervals.",
    },
    {
      topic: "NLP",
      priority: "medium",
      currentLevel: "Beginner",
      requiredLevel: "Intermediate",
      recommendation: "Know tokenization, embeddings, and transformer basics.",
    },
    {
      topic: "Model Deployment",
      priority: "medium",
      currentLevel: "Beginner",
      requiredLevel: "Intermediate",
      recommendation: "Learn how a trained model becomes an API endpoint.",
    },
    {
      topic: "Cloud",
      priority: "low",
      currentLevel: "None",
      requiredLevel: "Intermediate",
      recommendation: "Familiarize with core AWS/GCP ML services at a high level.",
    },
    {
      topic: "MLOps",
      priority: "low",
      currentLevel: "None",
      requiredLevel: "Intermediate",
      recommendation: "Understand CI/CD for models and experiment tracking conceptually.",
    },
    {
      topic: "Docker",
      priority: "low",
      currentLevel: "Beginner",
      requiredLevel: "Intermediate",
      recommendation: "Learn to containerize a simple ML service.",
    },
  ],
  projects: [
    {
      id: "weather-forecasting",
      name: "Weather Forecasting",
      relevance: 92,
      technologies: ["Python", "Pandas", "Scikit-learn", "Machine Learning"],
      whatToKnow: [
        "The end-to-end pipeline: data ingestion, cleaning, feature engineering, and model selection.",
        "Why you chose a regression model over alternatives.",
        "How you validated results and measured error.",
      ],
      likelyQuestions: [
        "Why did you choose this algorithm?",
        "How did you handle missing data?",
        "Why did you select this evaluation metric?",
        "How did you prevent overfitting?",
        "How would you deploy this model?",
      ],
      conceptsToRevise: ["Regression", "Cross-validation", "Feature engineering", "RMSE vs MAE"],
      strength: 88,
      source: "found",
    },
    {
      id: "sentiment-analysis",
      name: "Sentiment Analysis Engine",
      relevance: 81,
      technologies: ["Python", "TensorFlow", "NLP", "Deep Learning"],
      whatToKnow: [
        "How text is converted into features (embeddings/tokenization).",
        "The architecture of your model and why.",
        "Class imbalance handling.",
      ],
      likelyQuestions: [
        "How did you preprocess the text data?",
        "What embedding approach did you use and why?",
        "How did you evaluate a classification model?",
        "How would you handle sarcasm or negation?",
      ],
      conceptsToRevise: ["Tokenization", "Embeddings", "Precision/Recall", "Softmax"],
      strength: 79,
      source: "found",
    },
  ],
  interviewQuestions: [
    { id: "t1", question: "What is overfitting in machine learning?", category: "technical", difficulty: "Medium", topic: "Machine Learning" },
    { id: "t2", question: "Explain the bias-variance trade-off.", category: "technical", difficulty: "Medium", topic: "Machine Learning" },
    { id: "t3", question: "How does gradient descent work?", category: "technical", difficulty: "Medium", topic: "Optimization" },
    { id: "t4", question: "What is the difference between a list and a tuple in Python?", category: "technical", difficulty: "Easy", topic: "Python" },
    { id: "t5", question: "Write a SQL query to find the second highest salary.", category: "technical", difficulty: "Medium", topic: "SQL" },
    { id: "t6", question: "Explain precision, recall, and F1 score.", category: "technical", difficulty: "Medium", topic: "Metrics" },
    { id: "r1", question: "Walk me through your Machine Learning internship at DataNova Analytics.", category: "resume", difficulty: "Easy", topic: "Experience", relatedTo: "DataNova Analytics" },
    { id: "r2", question: "What was your biggest contribution as a Research Assistant?", category: "resume", difficulty: "Medium", topic: "Experience", relatedTo: "University AI Lab" },
    { id: "r3", question: "Which skill on your resume are you strongest at, and why?", category: "resume", difficulty: "Easy", topic: "Skills" },
    { id: "p1", question: "Why did you choose this algorithm for Weather Forecasting?", category: "projects", difficulty: "Medium", topic: "ML Projects", relatedTo: "Weather Forecasting" },
    { id: "p2", question: "How did you handle missing data in Weather Forecasting?", category: "projects", difficulty: "Medium", topic: "Data", relatedTo: "Weather Forecasting" },
    { id: "p3", question: "How did you preprocess text in the Sentiment Analysis Engine?", category: "projects", difficulty: "Medium", topic: "NLP", relatedTo: "Sentiment Analysis Engine" },
    { id: "h1", question: "Tell me about yourself.", category: "hr", difficulty: "Easy", topic: "Behavioral" },
    { id: "h2", question: "Describe a time you faced a difficult technical challenge.", category: "hr", difficulty: "Medium", topic: "Behavioral" },
    { id: "h3", question: "Where do you see yourself in five years?", category: "hr", difficulty: "Easy", topic: "Behavioral" },
    { id: "rs1", question: "How would you design an ML pipeline for a recommendation system?", category: "role-specific", difficulty: "Hard", topic: "System Design" },
    { id: "rs2", question: "How do you monitor a model in production?", category: "role-specific", difficulty: "Hard", topic: "MLOps" },
    { id: "rs3", question: "How would you deploy a trained model as an API?", category: "role-specific", difficulty: "Medium", topic: "Deployment" },
  ],
  resumeImprovements: [
    {
      id: "imp1",
      impact: "high",
      title: "Add measurable results to your projects",
      before: "Created a machine learning model.",
      after: "Developed a machine learning model achieving 91% accuracy on historical weather data.",
    },
    {
      id: "imp2",
      impact: "high",
      title: "Quantify your internship impact",
      before: "Worked on data pipelines during internship.",
      after: "Built data pipelines that reduced preprocessing time by 40% across 3 datasets.",
    },
    { id: "imp3", impact: "medium", title: "Improve ATS keywords", description: "Mirror the exact terminology from ML Engineer job descriptions (e.g. 'feature engineering', 'model evaluation')." },
    { id: "imp4", impact: "medium", title: "Add GitHub links", description: "Link each project to a public repository so recruiters can verify your work." },
    { id: "imp5", impact: "medium", title: "Strengthen project descriptions", description: "Lead each bullet with an action verb and end with an outcome." },
    { id: "imp6", impact: "low", title: "Add certifications", description: "Include relevant ML/cloud certifications if you complete them." },
    { id: "imp7", impact: "low", title: "Add relevant achievements", description: "Mention hackathons, competitions, or academic honors." },
  ],
  careerRoadmap: [
    { step: 1, title: "Strengthen Python", description: "Master advanced Python and clean coding patterns.", status: "done", estimate: "Completed" },
    { step: 2, title: "Improve SQL", description: "Get comfortable with window functions and complex joins.", status: "in-progress", estimate: "2 weeks" },
    { step: 3, title: "Learn Docker", description: "Containerize a small ML service end-to-end.", status: "upcoming", estimate: "2 weeks" },
    { step: 4, title: "Build an ML deployment project", description: "Deploy a model as a REST API on the cloud.", status: "upcoming", estimate: "3 weeks" },
    { step: 5, title: "Practice technical interviews", description: "Complete 30+ mock interview questions across topics.", status: "upcoming", estimate: "4 weeks" },
    { step: 6, title: "Apply for Machine Learning Engineer roles", description: "Target roles that match your strengthened profile.", status: "upcoming", estimate: "Ongoing" },
  ],
};
